In [1]:
import pandas as pd
import numpy as np
import random
import matplotlib.pyplot as plt
%matplotlib inline

## preliminary analysis

In [4]:
train_data = pd.read_csv('..\\Bitcoint_Data\\train_timeseries.csv')

In [10]:
train_data['date'] = pd.to_datetime(train_data['date'])

In [12]:
train_data.head()

,date,open,high,low,close,market_cap,avg_block_size,blocks_size,cost_per_transaction_percent,cost_per_transaction,...,transactions_per_sec_min,transactions_per_sec_max,utxo_count_mean,utxo_count_stddev,utxo_count_min,utxo_count_max,news_stories_total,news_stories_positive,news_stories_negative,news_stories_neutral
0,2018-11-30,4289.09,4322.98,3942.82,4017.27,6.990464e+10,1.209791,192791.5434,0.328777,21.396147,...,1.183333,17.700000,58319967.38,27106.89859,58281148,58355400,1071,356,549,166
1,2018-11-29,4269.00,4413.02,4145.77,4278.85,7.445102e+10,1.202130,192669.3545,0.625105,23.508462,...,1.283333,27.916667,58252488.42,15831.47820,58212951,58269350,1096,389,521,186
2,2018-11-28,3822.47,4385.90,3822.47,4257.42,7.407256e+10,1.111968,192543.1309,0.762892,24.411103,...,0.433333,33.850000,58186459.38,13193.95528,58165046,58213488,1187,409,583,195
3,2018-11-27,3765.95,3862.96,3661.01,3820.72,6.646897e+10,1.071254,192411.9186,0.730799,23.399753,...,1.683333,17.083333,58159562.88,9943.16102,58132945,58176825,1239,424,597,218
4,2018-11-26,4015.07,4107.14,3643.92,3779.13,6.573929e+10,1.186164,192271.5843,0.741989,21.745022,...,1.166667,27.200000,58120822.67,13528.76274,58082636,58135200,1343,454,670,219